version: '3'

services:

  mysql:
    image: jahrik/arm-mysql:aarch64
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - /mnt/g1/mysql:/var/lib/mysql/
    ports:
      - 3306:3306
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.arch == aarch64
