version: '3.7'

services:

  mysql:
    image: "jahrik/mysql:${TAG}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
#      - ghost
      - monitor
    volumes:
      - /mnt/g1/mysql:/var/lib/mysql/
    ports:
      - 3306:3306
    deploy:
      mode: replicated
      replicas: 1
#       placement:
#         constraints:
#           - node.labels.arch == aarch64

networks:
#   ghost:
#     name: ghost
#     driver: overlay
#     external: true
  monitor:
    name: monitor
    driver: overlay
    external: true
