version: '3'

services:

  visualizer:
    image: jahrik/arm-visualizer:arm32v7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8081:8080
    deploy:
      mode: global
